pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'us-east-1'
        ECR_REPO = '7673-9771-0460.dkr.ecr.us-east-1.amazonaws.com/nti_jenkins'
        GITHUB_REPO_URL = 'https://github.com/shrifzain/3-tier/edit/master/frontend'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'master', url: "${GITHUB_REPO_URL}"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${ECR_REPO}:${DOCKER_IMAGE_TAG}", ".")
                }
            }
        }

        stage('Tag Docker Image') {
            steps {
                script {
                    docker.tag("${ECR_REPO}:${DOCKER_IMAGE_TAG}", "${ECR_REPO}:${DOCKER_IMAGE_TAG}")
                }
            }
        }

        stage('Push Docker Image to ECR') {
            steps {
                script {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws_ecr', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                        sh "aws ecr-public get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}"
                        docker.push("${ECR_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }
    }
}
